== Annotation rules

== Modification

=== Modification of methods

* explicitly empty methods are `@NotModified` (even though they can be non-static and `void`)
* non-static `void` methods, `@Fluent` methods, constructors are `@Modified` by default
* methods in an immutable type are `@NotModified` by default. Overriding this will result in a warning.

=== Modification of parameter

* always `@NotModified` in methods of `@Container` types
* always `@NotModified` if the parameter type is `@Immutable`, with or without hidden content
* if the method is an override, then the disjunction of the values for the override is taken
* otherwise, the default value for that type is taken.

== Independence

Is the parameter or method return value linked to any of the fields? In other words, can a modification
to an argument or return value imply a modification on the fields of the object, or vice versa?
If not, then the parameter or method is termed _independent_.

Immutable objects are always independent, by definition: no modifications are possible.
Immutable objects with hidden content can be either independent, or independent allowing for hidden content.
When allowing for hidden content, we ignore potential modifications in the hidden content.

=== Independence of method

* always `@Independent` when the method belongs to a type which is marked `@Immutable` or `@Independent`
* always `@Independent` when the method return type is `@Immutable`.
* the default value is `@Dependent` for methods of a mutable return type
* the default value is `@Independent(hc = true)` for methods of `@Immutable(hc = true)` return type.

Only in situations that differ from the situations above, the annotation will be printed by the decorator.

=== Independence of parameter

* always `@Independent` when the parameter belongs to a method in a type which is marked `@Immutable` or `@Independent`
* always `@Independent` when the parameter type is `@Immutable`.
* the default value is `@Dependent` for parameters of a mutable type
* the default value is `@Independent(hc = true)` for parameters of `@Immutable(hc = true)` type.

Only in situations that differ from the situations above, the annotation will be printed by the decorator.

== Immutability

Broadly speaking, immutability is the combination of non-modification and independence.


== Container

A type is termed a container when none of the parameters of its methods and constructors is modifying.


Both methods and parameters can also have the `@Container` property, as a restriction on the argument
or concrete return type in overrides.

A method is computed to be a `@Container` when

* its return type is an array, a primitive, void, an unbound type parameter, a `@Container` type
* overrides
* if the method is `@Identity`, then the result depends on the container property of the first parameter.

If a parameter of functional interface type is marked `@Container`, then the SAM cannot be modifying.